### ISSUE TITLE
Libreria Verificación

### ISSUE THREAD

**Issue by Manruelop** [Manruelop/CreacionAdminVotaciones#1]
Al implementar el proyecto del curso pasado, nos encontramos con un error de falta de libraria, faltaba la librería Verification. 

Para resolver el problema, tuvimos que usar un comando maven para importar manualmente la librería Verification, ya que maven no era capaz de encontrar la libreria por si sola.

**Comment by rafaka** [comment]
Librería de Verificación integrada.
