### ISSUE TITLE
Recuento: Actualización direccionamiento a nuestra nueva URL

### ISSUE THREAD

**Issue by rafaeldrs** [Manruelop/CreacionAdminVotaciones#3]
Es necesaria una actualización en el direccionamiento para la realización de recuentos.

Para realizar un recuento de una votación debe permitirse al usuario establecer los siguientes parámetros:
    \* Votación a la que se desea acceder
    \* Codificación de esos votos
    \* Segmentación de los resultados

Codificación de los votos y Segmentación de los resultados son opcionales, aunque lógicamente si los votos están codificados y no se especifica la codificación especial, no funcionará correctamente.

Ejemplos:
Recuento de la votación 2:
https://recuento.herokuapp.com/count/2

Recuento de la votación 1 que tiene codificación especial:
https://recuento.herokuapp.com/count/1?cod=especial

Recuento de la votación 2 con segmentación por género:
https://recuento.herokuapp.com/count/2?segment=gender

Recuento de la votación 1 con codificación especial y segmentado por género
https://recuento.herokuapp.com/count/1?cod=especial&segment=gender

igual pero por comunidad autónoma
https://recuento.herokuapp.com/count/1?cod=especial&segment=aut_com

Para más información https://recuento.herokuapp.com/ o respuesta en esta misma incidencia.

Un saludo.

**Comment by rafaeldrs** [comment]
Olvidé comentar que debido a que la verificación de votos se realiza en un servidor en la India (aunque el nuestro está en Europa), el tiempo de cálculo de una votación puede ser de 10-20 segundos

**Comment by rafaeldrs** [comment]
Editado: Sería necesario consultar al usuario si quiere visualizar los resultados. En cuyo caso las urls cambiarían y se añadiría "/charts" detrás del número de la votación. Por ejemplo en las URLs de arriba:

https://recuento.herokuapp.com/count/2/charts
https://recuento.herokuapp.com/count/1/charts?cod=especial
https://recuento.herokuapp.com/count/2/charts?segment=gender
https://recuento.herokuapp.com/count/1/charts?cod=especial&segment=gender
https://recuento.herokuapp.com/count/1/charts?cod=especial&segment=aut_com

Como se puede ver son iguales pero con "/chars" detras del número de votación a consultar.

Para más información, responded sobre esta incidencia.

**Comment by rafaka** [comment]
Se decidido acoplar a otro subsistema. Incidencia cerrada.
