### ISSUE TITLE
Modificación para integración continua

### ISSUE THREAD

**Issue by jeparca** [Manruelop/CreacionAdminVotaciones#5]
Descripción:
Esta incidencia es un cambio a realizar en la gestión de la construcción, de forma que incorpore la librería de verificación automáticamente en el repositorio maven que se use a la hora de compilar. Los cambios a realizar en el archivo pom.xml son los siguientes:

Sección repositories:

```
    <repository>
        <id>jeparca</id>
        <url>http://mvnrepo.jeparca.com:8080/repository/egcVerificacion</url>
    </repository>
```

Sección dependencies:

```
             <dependency>
        <groupId>EGC</groupId>
        <artifactId>Verificacion</artifactId>
        <version>2.1.3</version>
    </dependency>
```

Esto incorporará automáticamente la librería.

**Comment by Redax94** [comment]
Integración completada con este modulo y añadido el repositorio y dependencias.
