### ISSUE TITLE
Inclusión del repositorio en la organización

### ISSUE THREAD

**Issue by juanmtriguero** [Manruelop/CreacionAdminVotaciones#8]
Por favor, incluid el repositorio de vuestro proyecto al repositorio de la organización de EGC del curso 2015/2016 del Grupo 2 (tarde), en la dirección: https://github.com/AgoraUS1516G2

El coordinador de vuestro proyecto ha sido invitado a dicha organización para tal efecto.

**Comment by Redax94** [comment]
Ya se subió.
